language: node_js
node_js:
   - "node"
before_script:
- npm install -g grunt-cli
after_script:
  - grunt retire
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: workshopdevops
